#!/usr/bin/env python

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from collections import defaultdict
import argparse
import cv2
import glob
import logging
import os
import sys
import time
import numpy as np
import json
import re
from datetime import datetime

from caffe2.python import workspace

from detectron.core.config import assert_and_infer_cfg
from detectron.core.config import cfg
from detectron.core.config import merge_cfg_from_file
from detectron.utils.io import cache_url
from detectron.utils.timer import Timer
import detectron.core.test_engine as infer_engine
import detectron.utils.c2 as c2_utils

import pycocotools.mask as mask_util
from skimage import measure

c2_utils.import_detectron_ops()

# OpenCL may be enabled by default in OpenCV3; disable it because it's not
# thread safe and causes unwanted GPU memory allocations.
cv2.ocl.setUseOpenCL(False)

MAX_DIMENSION_SHORT_SIDE = 800


def parse_args():
    parser = argparse.ArgumentParser(description='FamilySearch RCNN-based Article Segmenter')
    parser.add_argument(
        '--cfg',
        dest='cfg',
        help='cfg model file (default: /home/ubuntu/work/detectron/configs/fs/artseg.yaml)',
        default='/home/ubuntu/work/detectron/configs/fs/artseg.yaml',
        type=str
    )
    parser.add_argument(
        '--wts',
        dest='weights',
        help='weights model file (default: /home/ubuntu/work/detectron/models/artseg-es-1k.pkl)',
        default='/home/ubuntu/work/detectron/models/artseg-es-1k.pkl',
        type=str
    )
    parser.add_argument(
        '--thresh',
        dest='thresh',
        help='Threshold for keeping detections (default: 0.7)',
        default=0.7,
        type=float
    )
    parser.add_argument(
        '--output-file',
        dest='output_file',
        help='directory for output (default: /tmp/artseg/annotations.json)',
        default='/tmp/artseg/annotations.json',
        type=str
    )
    parser.add_argument(
        '--image-ext',
        dest='image_ext',
        help='image file name extension (default: jpg)',
        default='jpg',
        type=str
    )
    parser.add_argument(
        'im_or_folder', help='image or folder of images', default=None
    )

    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(1)
    return parser.parse_args()


_category_map = {
    'baptism-para': 1,
    'note': 2,
    'record-num': 3
}

_r_category_map = {
    1: 'baptism-para',
    2: 'note',
    3: 'record-num'
}


def setup_logging(name):
    FORMAT = '%(levelname)s %(filename)s:%(lineno)4d: %(message)s'
    logging.root.handlers = []
    logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"), format=FORMAT, stream=sys.stdout)
    logger = logging.getLogger(name)
    return logger


def new_json():
    data = {}

    info = {
        'description': 'FamilySearch Article Segmentation',
        'url': 'http://www.familysearch.org',
        'year': int(datetime.now().strftime('%Y')),
        'contributor': 'FamilySearch International',
        'date_created': datetime.now().strftime('%Y/%m/%d')
    }

    data['info'] = info

    licenses = [
        {
            'url': 'http://www.familysearch.org',
            'id': 1,
            'name': 'Proprietary Data. All Rights Reserved, FamilySearch International, 2019'
        }
    ]

    data['licenses'] = licenses
    data['images'] = []
    data['annotations'] = []

    categories = []
    for (k, v) in _category_map.items():
        category = {
            'supercategory': 'region',
            'id': v,
            'name': k
        }
        categories.append(category)

    data['categories'] = categories
    return data


def bbox2segmentation(bbox):
    (x0, y0, w, h) = bbox
    x1 = x0 + w
    y1 = y0 + h
    return [x0, y0, x1, y0, x1, y1, x0, y1]


def bbox_area(bbox):
    (x0, y0, w, h) = bbox
    return w * h


def convert_from_cls_format(cls_boxes, cls_segms, cls_keyps):
    """Convert from the class boxes/segms/keyps format generated by the testing
    code.
    """
    box_list = [b for b in cls_boxes if len(b) > 0]
    if len(box_list) > 0:
        boxes = np.concatenate(box_list)
    else:
        boxes = None
    if cls_segms is not None:
        segms = [s for slist in cls_segms for s in slist]
    else:
        segms = None
    if cls_keyps is not None:
        keyps = [k for klist in cls_keyps for k in klist]
    else:
        keyps = None
    classes = []
    for j in range(len(cls_boxes)):
        classes += [j] * len(cls_boxes[j])
    return boxes, segms, keyps, classes


def make_bboxes(boxes):
    if boxes is None:
        return []
    bboxes = []
    areas = (boxes[:, 2] - boxes[:, 0]) * (boxes[:, 3] - boxes[:, 1])
    sorted_inds = np.argsort(-areas)
    for i in sorted_inds:
        bbox = boxes[i, :4]
        score = boxes[i, -1]
        x0, y0, w, h = (int(bbox[0]), int(bbox[1]), int(bbox[2] - bbox[0]), int(bbox[3] - bbox[1]))
        bboxes.append(([x0, y0, w, h], score))
    return bboxes


def main(args):
    logger = logging.getLogger(__name__)

    merge_cfg_from_file(args.cfg)
    cfg.NUM_GPUS = 1
    args.weights = cache_url(args.weights, cfg.DOWNLOAD_CACHE)
    assert_and_infer_cfg(cache_urls=False)

    assert not cfg.MODEL.RPN_ONLY, \
        'RPN models are not supported'
    assert not cfg.TEST.PRECOMPUTED_PROPOSALS, \
        'Models that require precomputed proposals are not supported'

    model = infer_engine.initialize_model_from_cfg(args.weights)

    if os.path.isdir(args.im_or_folder):
        im_list = glob.iglob(args.im_or_folder + '/*.' + args.image_ext)
    else:
        im_list = [args.im_or_folder]

    if not os.path.exists('/tmp/artseg'):
        os.mkdir('/tmp/artseg')

    data = new_json()
    next_img_id = 1
    next_annotation_id = 1

    for i, im_name in enumerate(im_list):

        image_file_name = os.path.basename(im_name)

        logger.info('Processing {}'.format(im_name))
        im = cv2.imread(im_name)
        im_h, im_w, img_c = im.shape
        scale_factor = 1.0
        if im_h < im_w:
            if im_h > MAX_DIMENSION_SHORT_SIDE:
                scale_factor = float(MAX_DIMENSION_SHORT_SIDE) / float(im_h)
        else:
            if im_w > MAX_DIMENSION_SHORT_SIDE:
                scale_factor = float(MAX_DIMENSION_SHORT_SIDE) / float(im_w)

        if scale_factor != 1.0:
            im = cv2.resize(im, (int(round(float(im_w) * scale_factor)), int(round(float(im_h) * scale_factor))))

        timers = defaultdict(Timer)
        t = time.time()
        with c2_utils.NamedCudaScope(0):
            cls_boxes, cls_segms, cls_keyps = infer_engine.im_detect_all(model, im, None, timers=timers)
        logger.info('Inference time: {:.3f}s'.format(time.time() - t))
        for k, v in timers.items():
            logger.info(' | {}: {:.3f}s'.format(k, v.average_time))
        if i == 0:
            logger.info(
                ' \ Note: inference on the first image will be slower than the '
                'rest (caches and auto-tuning need to warm up)'
            )

        if isinstance(cls_boxes, list):

            (boxes, segms, keyps, classes) = convert_from_cls_format(cls_boxes, cls_segms, cls_keyps)

            m = re.match('([0-9]{9})_([0-9]{5})', image_file_name)
            dgs_str = m.group(1)
            img_num_str = m.group(2)

            image_url = 'https://das.familysearch.org/das/v2/dgs:' + dgs_str + '.' + dgs_str + '_' + img_num_str + '/$dist'

            bboxes = make_bboxes(boxes)
            logger.info('{} boxes found'.format(len(bboxes)))

            image = {
                'license': 1,
                'file_name': image_file_name,
                'coco_url': image_url,
                'height': im_h,
                'width': im_w,
                'date_captured': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'flickr_url': image_url,
                'id': next_img_id
            }

            data['images'].append(image)

            if boxes is not None:
                for j, bbox in enumerate(bboxes):

                    (bbox, score1) = bboxes[j]
                    score2 = boxes[j, -1]
                    logging.debug('score1: {} score2: {}'.format(score1, score2))

                    if score2 >= args.thresh:
                        bbox = [x / scale_factor for x in bbox]

                        annotation = {
                            'score': float(score2),
                            'segmentation': bbox2segmentation(bbox),
                            'area': bbox_area(bbox),
                            'iscrowd': 0,
                            'image_id': next_img_id,
                            'bbox': bbox,
                            'category_id': classes[j],
                            'id': next_annotation_id
                        }

                        data['annotations'].append(annotation)
                        next_annotation_id += 1

                    else:
                        logging.info('Not keeping box with confidence {} below threshold of {}'.format(score2, args.thresh))


            next_img_id += 1

        else:
            logger.info('Nothing found in image {}'.format(image_file_name))

    with open(args.output_file, 'w') as outfile:
        json.dump(data, outfile, indent=4)


if __name__ == '__main__':
    workspace.GlobalInit(['caffe2', '--caffe2_log_level=0'])
    setup_logging(__name__)
    args = parse_args()
    main(args)


