#!/usr/bin/env python

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from collections import defaultdict
import argparse
import cv2
import glob
import logging
import os
import sys
import time
import numpy as np

from datetime import datetime
import xml.etree.ElementTree as etree
from xml.etree.ElementTree import Element, SubElement, Comment, tostring
from xml.dom import minidom

from shapely.geometry import Polygon
from shapely.geometry import LineString
from shapely.ops import nearest_points
from shapely.ops import unary_union
from shapely import speedups
from rtree import index


from caffe2.python import workspace

from detectron.core.config import assert_and_infer_cfg
from detectron.core.config import cfg
from detectron.core.config import merge_cfg_from_file
from detectron.utils.io import cache_url
from detectron.utils.timer import Timer
import detectron.core.test_engine as infer_engine
import detectron.utils.c2 as c2_utils

import pycocotools.mask as mask_util
from skimage import measure

c2_utils.import_detectron_ops()

# OpenCL may be enabled by default in OpenCV3; disable it because it's not
# thread safe and causes unwanted GPU memory allocations.
cv2.ocl.setUseOpenCL(False)

MAX_DIMENSION_SHORT_SIDE = 800


def parse_args():
    parser = argparse.ArgumentParser(description='FamilySearch Mask-R-CNN-based Line Segmenter')
    parser.add_argument(
        '--cfg',
        dest='cfg',
        help='cfg model file (default: /home/ubuntu/work/detectron/configs/fs/lineseg-e2e_mask_rcnn-R-101-FPN-2x.yaml)',
        default='/home/ubuntu/work/detectron/configs/fs/lineseg-e2e_mask_rcnn-R-101-FPN-2x.yaml',
        type=str
    )
    parser.add_argument(
        '--wts',
        dest='weights',
        help='weights model file (default: /home/ubuntu/work/detectron/models/maskrcnn-lineseg-640k.pkl)',
        default='/home/ubuntu/work/detectron/models/maskrcnn-lineseg-640k.pkl',
        type=str
    )
    parser.add_argument(
        '--thresh',
        dest='thresh',
        help='Threshold for keeping detections (default: 0.5)',
        default=0.9,
        type=float
    )
    parser.add_argument(
        '--output-dir',
        dest='output_dir',
        help='directory for output (default: /tmp/line_segmentation)',
        default='/tmp/line_segmentation',
        type=str
    )
    parser.add_argument(
        '--image-ext',
        dest='image_ext',
        help='image file name extension (default: jpg)',
        default='jpg',
        type=str
    )
    parser.add_argument(
        'im_or_folder', help='image or folder of images', default=None
    )

    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(1)
    return parser.parse_args()


_category_map = {
    'handwritten-line': 1,
    'machine-print-line': 2,
    'separator': 3,
    'line-drawing': 4,
    'graphic': 5
}

_r_category_map = {
    1: 'handwritten-cursive',
    2: 'printed',
    3: 'separator',
    4: 'line-drawing',
    5: 'graphic'
}


def setup_logging(name):
    FORMAT = '%(levelname)s %(filename)s:%(lineno)4d: %(message)s'
    logging.root.handlers = []
    logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"), format=FORMAT, stream=sys.stdout)
    logger = logging.getLogger(name)
    return logger


def prettify(elem):
    rough_string = etree.tostring(elem, 'utf-8')
    reparsed = minidom.parseString(rough_string)
    return reparsed.toprettyxml(indent='    ')


def calculate_aspect_ratio(poly):
    (minx, miny, maxx, maxy) = poly.bounds
    aspect_ratio = (maxx - minx) / (maxy - miny)
    return aspect_ratio


def determine_orientation(aspect_ratio):
    line_orientation = 'undetermined'
    if aspect_ratio > 2.0:
        line_orientation = 'horizontal'
    elif aspect_ratio < 0.5:
        line_orientation = 'vertical'
    return line_orientation


def new_xml():
    root = Element('top')
    root.tag = 'PcGts'
    root.set('xmlns', 'http://schema.primaresearch.org/PAGE/gts/pagecontent/2017-07-15')
    root.set('xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance')
    root.set('xsi:schemaLocation',
             'http://schema.primaresearch.org/PAGE/gts/pagecontent/2017-07-15 http://schema.primaresearch.org/PAGE/gts/pagecontent/2017-07-15/pagecontent.xsd')
    metadata = SubElement(root, 'Metadata')
    creator = SubElement(metadata, 'Creator')
    creator.text = 'FamilySearch International'
    created = SubElement(metadata, 'Created')
    created.text = datetime.now().strftime('%Y-%m-%dT%H:%M:%S')
    last_change = SubElement(metadata, 'LastChange')
    last_change.text = datetime.now().strftime('%Y-%m-%dT%H:%M:%S')

    return root


def convert_from_cls_format(cls_boxes, cls_segms, cls_keyps):
    """Convert from the class boxes/segms/keyps format generated by the testing
    code.
    """
    box_list = [b for b in cls_boxes if len(b) > 0]
    if len(box_list) > 0:
        boxes = np.concatenate(box_list)
    else:
        boxes = None
    if cls_segms is not None:
        segms = [s for slist in cls_segms for s in slist]
    else:
        segms = None
    if cls_keyps is not None:
        keyps = [k for klist in cls_keyps for k in klist]
    else:
        keyps = None
    classes = []
    for j in range(len(cls_boxes)):
        classes += [j] * len(cls_boxes[j])
    return boxes, segms, keyps, classes


def make_bboxes(boxes):
    if boxes is None:
        return []
    bboxes = []
    areas = (boxes[:, 2] - boxes[:, 0]) * (boxes[:, 3] - boxes[:, 1])
    sorted_inds = np.argsort(-areas)
    for i in sorted_inds:
        bbox = boxes[i, :4]
        score = boxes[i, -1]
        x0, y0, w, h = (int(bbox[0]), int(bbox[1]), int(bbox[2] - bbox[0]), int(bbox[3] - bbox[1]))
        bboxes.append(([x0, y0, w, h], score))
    return bboxes


def convert_to_xml_coords(segmentation):
    if len(segmentation) == 0:
        return ''
    new_segmentation = segmentation[0]
    coord_string = ''
    i = 0
    while i < len(new_segmentation):
        x = new_segmentation[i]
        y = new_segmentation[i + 1]
        if i == 0:
            coord_string += '{},{}'.format(int(x), int(y))
        else:
            coord_string += ' {},{}'.format(int(x), int(y))
        i += 2
    return coord_string


def poly2points(poly):
    seg = []
    for (x,y) in list(poly.exterior.coords):
        seg.append(x)
        seg.append(y)
    return seg


def points2poly(pts):
    pts2 = []
    assert len(pts) % 2 == 0
    i = 0
    while i < len(pts):
        x = pts[i]
        y = pts[i + 1]
        pts2.append((x, y))
        i += 2
    poly = Polygon(pts2)
    return poly


def fuse_segmentation(segmentation):
    # TODO: rather than fuse along a line between the two closet points, the better thing would be to connect along darker pixels between the two shapes

    if len(segmentation) == 1:
        return segmentation[0]
    else:
        logging.debug('Fusing {} segments'.format(len(segmentation)))
        polys = []

        for pts in segmentation:
            poly = points2poly(pts)
            polys.append(poly)

        new_poly = polys[0]

        polys.sort(key=lambda x: x.area, reverse=True)

        for p in polys:
            logging.debug('{}'.format(p.area))

        for (i, poly) in enumerate(polys):
            area_before = new_poly.area
            (pt1, pt2) = nearest_points(new_poly, poly)
            bridge = LineString([pt1, pt2]).buffer(4.0)
            geoms = [new_poly, poly, bridge]
            new_poly = unary_union(geoms)
            logging.debug('Combined area should be at least {}.  It is {}'.format(area_before + poly.area, new_poly.area))

        s_pts = list(new_poly.exterior.coords)
        points = []

        for (x, y) in s_pts:
            points.append(x)
            points.append(y)

        return points


def calc_area(segmentation):
    area = 0.0
    for pts in segmentation:
        poly = points2poly(pts)
        area += poly.area
    return area


def identify_bad(scores, category_ids, polygons, spatial_index, avg_line_orientation):
    bad = {}
    for (i, poly) in enumerate(polygons):
        try:
            bad[i] #skip if already ID'ed as bad
        except KeyError:
            ar = calculate_aspect_ratio(poly)
            line_orientation = determine_orientation(ar)
            category_id = category_ids[i]
            score = scores[i]
            overlappers = list(spatial_index.intersection(poly.bounds))
            overlappers.remove(i)

            if avg_line_orientation != 'undetermined' and (category_id == 1 or category_id == 2) and line_orientation != 'undetermined' and score < 0.5:
                if line_orientation != avg_line_orientation:
                    good_overlapper_count = 0
                    for ol in overlappers:
                        if category_ids[ol] == 1 or category_ids[ol] == 2:
                            if determine_orientation(calculate_aspect_ratio(polygons[ol])) == avg_line_orientation:
                                good_overlapper_count += 1
                    if good_overlapper_count >= 3:  #cuts across 3 or more good lines
                        bad[i] = True
                        continue

            for ol in overlappers:
                a = poly
                b = polygons[ol]
                a_idx = i
                b_idx = ol
                iarea = a.intersection(b).area
                iou = iarea / a.union(b).area
                if iou > 0.5:
                    #eliminate the region with a lower IoU score
                    if scores[b_idx] < scores[a_idx]:
                        bad[b_idx] = True
                    else:
                        bad[a_idx] = True
                else:
                    if iarea / b.area > 0.7: #b contained within a, eliminate b
                        bad[b_idx] = True
                    elif iarea / a.area > 0.7: #a contained within b, eliminate a
                        bad[a_idx] = True
                    else:
                        pass #both a and b survive for now
                    pass

    return bad


def main(args):
    logger = logging.getLogger(__name__)

    merge_cfg_from_file(args.cfg)
    cfg.NUM_GPUS = 1
    args.weights = cache_url(args.weights, cfg.DOWNLOAD_CACHE)
    assert_and_infer_cfg(cache_urls=False)

    assert not cfg.MODEL.RPN_ONLY, \
        'RPN models are not supported'
    assert not cfg.TEST.PRECOMPUTED_PROPOSALS, \
        'Models that require precomputed proposals are not supported'

    if speedups.available:
        speedups.enable()
    else:
        logging.info('No shapely speedups! :(')

    model = infer_engine.initialize_model_from_cfg(args.weights)

    if os.path.isdir(args.im_or_folder):
        im_list = glob.iglob(args.im_or_folder + '/*.' + args.image_ext)
    else:
        im_list = [args.im_or_folder]

    if not os.path.exists(args.output_dir):
        os.mkdir(args.output_dir)

    for i, im_name in enumerate(im_list):

        t0 = time.time()

        image_file_name = os.path.basename(im_name)

        ext = 'xml'

        out_name = os.path.join(
            args.output_dir, '{}'.format(os.path.splitext(image_file_name)[0] + '.' + ext)
        )
        logger.info('Processing {} -> {}'.format(im_name, out_name))
        im = cv2.imread(im_name)
        im_h, im_w, img_c = im.shape
        scale_factor = 1.0
        if im_h < im_w:
            if im_h > MAX_DIMENSION_SHORT_SIDE:
                scale_factor = float(MAX_DIMENSION_SHORT_SIDE) / float(im_h)
        else:
            if im_w > MAX_DIMENSION_SHORT_SIDE:
                scale_factor = float(MAX_DIMENSION_SHORT_SIDE) / float(im_w)

        if scale_factor != 1.0:
            im = cv2.resize(im, (int(round(float(im_w) * scale_factor)), int(round(float(im_h) * scale_factor))))

        logger.info('Image prep time: {:.3f}s'.format(time.time() - t0))

        timers = defaultdict(Timer)
        t1 = time.time()
        with c2_utils.NamedCudaScope(0):
            cls_boxes, cls_segms, cls_keyps = infer_engine.im_detect_all(model, im, None, timers=timers)
        logger.info('Inference time: {:.3f}s'.format(time.time() - t1))
        for k, v in timers.items():
            logger.info(' | {}: {:.3f}s'.format(k, v.average_time))
        if i == 0:
            logger.info(
                ' \ Note: inference on the first image will be slower than the '
                'rest (caches and auto-tuning need to warm up)'
            )

        t2 = time.time()
        if isinstance(cls_boxes, list):

            (boxes, segms, keyps, classes) = convert_from_cls_format(cls_boxes, cls_segms, cls_keyps)

            bboxes = make_bboxes(boxes)
            logger.debug('{} lines found'.format(len(bboxes)))

            data = new_xml()
            page = SubElement(data, 'Page')
            page.set('imageFilename', image_file_name)
            page.set('imageWidth', str(im_w))
            page.set('imageHeight', str(im_h))
            tr = SubElement(page, 'TextRegion')
            tr.set('id', 'region0')
            coords = SubElement(tr, 'Coords')
            coords.set('points', '0,0 {},0 {},{} 0,{}'.format(im_w, im_w, im_h, im_h))

            next_line_id = 1
            next_sep_id = 1
            next_ld_id = 1
            next_gra_id = 1

            j = 0
            k = 0
            if segms is not None:
                aspect_ratios = []
                polygons = []
                spatial_index = index.Index()
                segmentations = []
                scores = []
                bboxen = []
                category_ids = []

                for segm in segms:
                    score = boxes[j, -1]
                    logging.debug('score: {}'.format(score))
                    if score >= args.thresh:
                        mask = mask_util.decode(segm)
                        segmentation = []
                        contours = measure.find_contours(mask, 0.5)
                        for contour in contours:
                            contour = np.flip(contour, axis=1)
                            seg = contour.ravel().tolist()
                            seg = [x / scale_factor for x in seg]
                            segmentation.append(seg)
                        if len(segmentation) > 0:
                            try:
                                segmentation = [fuse_segmentation(segmentation)]
                            except ValueError:
                                logging.debug('bad segment {}, skipping'.format(segmentation))
                                continue
                            segmentations.append(segmentation)
                            poly = points2poly(segmentation[0])
                            polygons.append(poly)
                            spatial_index.insert(k, poly.bounds)
                            bbox = bboxes[j][0]
                            bboxen.append(bbox)
                            scores.append(score)
                            category_id = classes[j]
                            if category_id == 1 or category_id == 2:
                                aspect_ratio = calculate_aspect_ratio(poly)
                                aspect_ratios.append(aspect_ratio)
                            category_ids.append(category_id)
                            k += 1

                    else:
                        logging.info('Not keeping line with confidence {} below threshold of {}'.format(score2, args.thresh))

                    j += 1

                try:
                    avg_aspect_ratio = sum(aspect_ratios) / float(len(aspect_ratios))
                except ZeroDivisionError:
                    avg_aspect_ratio = 1
                avg_line_orientation = determine_orientation(avg_aspect_ratio)

                bad = identify_bad(scores, category_ids, polygons, spatial_index, avg_line_orientation)

                for (l, bbox) in enumerate(bboxen):
                    try:
                        bad[l]
                    except KeyError:
                        category_id = category_ids[l]
                        score = scores[l]
                        poly = polygons[l]
                        segmentation = segmentations[l]

                        if _r_category_map[category_id] == 'handwritten-cursive' or _r_category_map[category_id] == 'printed':
                            elem = SubElement(tr, 'TextLine')
                            elem.set('production', _r_category_map[category_id])
                            elem.set('id', 'tl' + str(next_line_id))
                            next_line_id += 1
                        elif _r_category_map[category_id] == 'separator':
                            elem = SubElement(page, 'SeparatorRegion')
                            elem.set('id', 'sr' + str(next_sep_id))
                            next_sep_id += 1
                        elif _r_category_map[category_id] == 'line-drawing':
                            elem = SubElement(page, 'LineDrawingRegion')
                            elem.set('id', 'ldr' + str(next_ld_id))
                            next_ld_id += 1
                        else:  # graphic
                            elem = SubElement(page, 'GraphicRegion')
                            elem.set('id', 'gr' + str(next_gra_id))
                            next_gra_id += 1

                        coord_string = convert_to_xml_coords(segmentation)
                        coords = SubElement(elem, 'Coords')
                        coords.set('points', coord_string)

            with open(out_name, 'w') as outfile:
                outfile.write(prettify(data))

        else:
            logger.info('Nothing found in image {}'.format(image_file_name))

        logger.info('Cleanup and serialization time: {:.3f}s'.format(time.time() - t2))
        logger.info('Total time: {:.3f}s\n'.format(time.time() - t0))


if __name__ == '__main__':
    workspace.GlobalInit(['caffe2', '--caffe2_log_level=0'])
    setup_logging(__name__)
    args = parse_args()
    main(args)
